Update spec to v2
phantom/shortcuts pull request #3
Opened 2024-02-05 16:50 UTC by bfriel

2024-02-05 16:57 UTC, RyanHirsch-Phantom requested changes

2024-02-05 16:57 UTC, RyanHirsch-Phantom commented on README.md
>  | limitToCollections    | string[] | (Optional) A list of collection addresses that should display this shortcut. If provided, the client should only show the shortcut on collections that are in this
In v2 `limitToCollections` only applies to `"type": "collectible"` and the analogous property for `"type": "fungible"` is `limitToTokenAddresses`

2024-02-21 16:27 UTC, RyanHirsch-Phantom approved these changes

2024-03-11 18:29 UTC, merged

2025-01-08 20:13 UTC, Johnson1s reviewed
#3